# Generated by Django 5.0.6 on 2024-06-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')])),
                ('summer', models.CharField(choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')])),
                ('autumn', models.CharField(choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')])),
                ('spring', models.CharField(choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')])),
            ],
        ),
        migrations.CreateModel(
            name='PUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField()),
                ('beauty_title', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=60)),
                ('other_titles', models.CharField(max_length=60)),
                ('connect', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')])),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.coords')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.levels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.puser')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=250)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.pereval')),
            ],
        ),
    ]
