# Generated by Django 5.0.6 on 2024-06-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0003_alter_pereval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='autumn',
            field=models.CharField(blank=True, choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')], null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='spring',
            field=models.CharField(blank=True, choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')], null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='summer',
            field=models.CharField(blank=True, choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')], null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='winter',
            field=models.CharField(blank=True, choices=[('lvl1', '1'), ('lvl2', '2'), ('lvl3', '3')], null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='coords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perevals.coords'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perevals.levels'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'Post awaits moderation'), ('pending', 'Post taken for moderation'), ('accepted', 'Post accepted'), ('rejected', 'Post rejected')]),
        ),
        migrations.AlterField(
            model_name='puser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puser',
            name='otc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
