# Generated by Django 5.0.6 on 2024-06-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0006_alter_images_image_alter_images_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='perevals.puser'),
        ),
    ]
