# Generated by Django 5.0.6 on 2024-06-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevals', '0007_alter_pereval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='coords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perevals.coords'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perevals.levels'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='perevals.puser'),
        ),
    ]
